# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/373b5c55-68a5-4ffb-8643-d7e63b305ee1";
      fsType = "ext4";
    };

  fileSystems."/var/lib/docker" = 
    {
    device = "/dev/disk/by-uuid/ac83855a-f3b3-4066-bcf0-288349097e67";
    fsType = "btrfs";
    options = [ "subvol=@docker" "compress=zstd" "noatime" "nofail" ];
    };

  fileSystems."/mnt/data" = 
    {
    device = "/dev/disk/by-uuid/ac83855a-f3b3-4066-bcf0-288349097e67";
    fsType = "btrfs";
    options = [ "subvol=@data" "compress=zstd" "noatime" "nofail" ];
    };

  fileSystems."/mnt/misc" = 
    {
    device = "/dev/disk/by-uuid/ac83855a-f3b3-4066-bcf0-288349097e67";
    fsType = "btrfs";
    options = [ "subvol=@misc" "compress=zstd" "noatime" "nofail" ];
    };

  fileSystems."/mnt/backup" = 
    {
    device = "/dev/disk/by-uuid/ac83855a-f3b3-4066-bcf0-288349097e67";
    fsType = "btrfs";
    options = [ "subvol=@backup" "compress=zstd" "noatime" "nofail" ];
    };

  fileSystems."/mnt/media" = 
    {
    device = "/dev/disk/by-uuid/ac83855a-f3b3-4066-bcf0-288349097e67";
    fsType = "btrfs";
    options = [ "subvol=@media" "compress=zstd" "noatime" "nofail" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
